name: Deploy to Render on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      run: curl -X POST -d '{}' https://api.render.com/deploy/srv-ct32dltsvqrc738in4sg?key=PRfS6QR0X2M